steps:
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ["test"]
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ["assemble"]
  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/api-gateway', '.' ]
images: ["gcr.io/$PROJECT_ID/api-gateway"]